---
# tasks file for OULibraries.searchgateway
- name: clone searchgateway repo
  git:
    dest: "/srv/searchgateway/src"
    repo: "https://github.com/OULibraries/searchgateway.git"

- name: Let composer own php code
  file:
    path: /srv/searchgateway/src
    owner: composer
    group: wheel
    state: directory
    
- name: Composer install search gateway dependencies 
  become: yes
  become_user: composer
  shell: |
    scl enable rh-php56 '/opt/php/bin/composer.phar install'
  args:
    chdir: /srv/searchgateway/src
    creates: /srv/searchgateway/src/vendor


- name: Set default SELinux context for searchgateway files
  command: >
    semanage fcontext -a -t httpd_sys_rw_content_t  "/srv/searchgateway/src(/.*)?"
  become: yes

- name: Restore default SELinux context for search gateway files
  command: >
    restorecon -rv /srv/searchgateway/
  become: yes

# Setting this to wheel for now, but this probably needs more thought
- name: Set ownership and perms of search gateway code
  shell: |
    chgrp -R wheel /srv/searchgateway/src/
    chmod -R g+rwX /srv/searchgateway/src/

- name: Configure search gateway settings
  template:
    src: "secrets.php.j2"
    dest: "/srv/searchgateway/src/config/secrets.php"
    owner: root
    group: wheel
    mode: 0664

- name: Ensure app etc directory exists
  file:
    path: /srv/searchgateway/etc
    owner: nginx
    group: nginx
    state: directory

- name: Configure nginx for search gateway
  template:
    src: "search.inc.j2"
    dest: "/srv/searchgateway/etc/{{ searchgateway_nginx_stub }}.nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: Restart nginx to load new config
  service:
    name: "nginx"
    state: restarted
    enabled: yes

    
